### ISSUE TITLE
the trait `glium::Vertex` is not implemented for `obj::TexturedVertex`

### ISSUE THREAD

**Issue by teddy-otieno** [simnalamburt/obj-rs#40]
obj-rs = {version = "*", features = ["glium-support"]}, that is my dependecy in my Cargo.toml.  Cant pass the vertices to the vertex buffers. Apologies for my poor english

**Comment by simnalamburt** [comment]
Looks like obj-rs is not compatible with recent version of Glium. Are you using glium 0.26.0?

**Comment by teddy-otieno** [comment]
> Looks like obj-rs is not compatible with recent version of Glium. Are you using glium 0.26.0?

Yes I'm using the latest 0.26.0, is there any way to fix it because i this is the easiest to use OBJ library i could find.

**Comment by simnalamburt** [comment]
@teddy-otieno I'll fix it for you hang on

**Comment by simnalamburt** [comment]
Closed by https://github.com/simnalamburt/obj-rs/commit/6d29bcd9e15394fe47c087e3d8d0b61a2cb5e874

**Comment by teddy-otieno** [comment]
Thank you. Please update me when you're done

**Comment by simnalamburt** [comment]
@teddy-otieno I'm done! Try obj-rs v0.6.0 :)

**Comment by teddy-otieno** [comment]
Thank you very much
