### ISSUE TITLE
Seemingly no way to use include_bytes! for a file

### ISSUE THREAD

**Issue by aladvs** [simnalamburt/obj-rs#66]
Self explanatory. Loading an obj requires file::open, and has no option from loading from include_bytes!().

**Comment by simnalamburt** [comment]
That is not true. Use can use `Cursor<&[u8]>`. See next for the further details: https://doc.rust-lang.org/stable/std/io/struct.Cursor.html

**Comment by aladvs** [comment]
yep, thats why i immediately closed the issue.
