### ISSUE TITLE
Load larger models

### ISSUE THREAD

**Issue by aladvs** [simnalamburt/obj-rs#67]
Apologies for opening another "issue", but when loading extremely large models using load_obj(), I keep getting the

_'Unable to convert the index from usize'_

error. The documentation isn't very clear on load_obj, so how can I load larger models?

Thank you.

**Comment by simnalamburt** [comment]
Change `I` type parameter of `Obj` type from u16 into u32, u64, u128

###### References
- https://docs.rs/obj-rs/latest/obj/struct.Obj.html
