### ISSUE TITLE
obj::Obj does not derive Clone

### ISSUE THREAD

**Issue by theKidOfArcrania** [simnalamburt/obj-rs#71]
Should be an easy fix to add Clone deriving for `Obj` type

**Comment by theKidOfArcrania** [comment]
deriving Default may also sorta make sense (if you assume it as a no-name no-vertex object

**Comment by simnalamburt** [comment]
Published v0.7.2

**Comment by simnalamburt** [comment]
I've derived a few more traits

###### References
- https://github.com/simnalamburt/obj-rs/commit/be7cd75e4dfddb3873ab220f869bbb6d33ad8530
