### ISSUE TITLE
Error "Unable to convert the index from usize" is non-descriptive

### ISSUE THREAD

**Issue by nshyrei** [simnalamburt/obj-rs#72]
When loading large OBJ files using the library, an error occurs during index conversion, but the error message provided is not descriptive enough to help diagnose the root cause of the issue. The error simply states `Unable to convert the index from usize` without additional context, which makes it difficult to identify whether the issue is caused by integer overflow, incorrect index type, or some other factor.
Can we provide more context in the error message here like for example: 
- Print the length of the vector in question;
- Mention the target type `I`;
- Mention that the error happens during index conversion.

The code in question is: https://github.com/simnalamburt/obj-rs/blob/e8390de9fb4e5452a57f42e97d357d19b42e6d5f/obj-rs/src/lib.rs#L131

If anyone encounters a similar issue, the way to fix it is to specify the type of indices of your `obj::Obj` that you are loading, as the default type is `u16` which might not be enough for your case. An example fix looks like this:
```
fn load_model(path: &Path) -> Obj<obj::Vertex, u32> {
    let input = BufReader::new(File::open(path).expect(&format!("Failed to open {}", path.display())));

    load_obj(input).expect(&format!("Failed to load model at {}", path.display()))
}
```

**Comment by simnalamburt** [comment]
obj-rs v0.7.4 has been released. Your issue has been resolved. Thanks for your contribution

###### Reference
- https://crates.io/crates/obj-rs/0.7.4
